config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :users, only: [:delete]
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  
  include PgSearch::Model
  pg_search_scope :search_by_model_and_brand,
  against: [ :model, :brand ],
  using: {
      tsearch: { prefix: true }
  }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :cars
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
    @car = Car.find(params[:car_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @car = Car.find(params[:car_id])
    @car.update(status: "busy")
    @booking.car = @car
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def index
    @bookings = current_user.bookings
  end

  def show
     @booking = Booking.find(params[:car_id])
  end

  private

  def booking_params
    params.require(:booking).permit( :start_date, :end_date, :pickup_location, :insurance)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :find_id, only: [:edit, :update, :show, :delete]

  def index
    if params[:query].present?
      @cars = Car.search_by_model_and_brand(params[:query])

    else
      @cars = Car.all
    end
    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude
      }
    end


  end

  def new
    @car =  Car.new
  end

  def create
    @car =  Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    # @car =  Car.update(car_params)
    # if @car.save
    #   redirect_to root_path
    # else
    #   render :edit
    # end
  end

  def show
    @oneCar = Car.find(params[:id])
    @marker = [{ lat: @oneCar.latitude, lng: @oneCar.longitude}]
  end

  def delete
    # @car.destroy
  end

  private
  def car_params
    params.require(:car).permit(:model, :brand, :year, :location, :title, :price, :description, :photo)
  end

  def find_id
    @car = Car.find(params[:id])
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @car = Car.all.sample
    @car2 = Car.all.sample
    @car3 = Car.all.sample
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

    
    def resource_name
        :user
      end
      def resource
        @user ||= User.new
      end
      def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
      end
      
end

app/views/bookings/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col px-0">
			<h1 class="ml-0 title-showpage px-0" style="background-color: white">&nbsp;ALL BOOKINGS</h1>
		</div>
  </div>
     
  <div class="row inline-block">
      <br>      
    <% @bookings.each do |booking| %>
    <div class="col-6">
         <div class="postcard blue">
	        	<a class="postcard__img_link" href="#">
	        	<a href="<%=car_path(booking.car_id)%>">	<img class="postcard__img" src="<%= cl_image_path Car.find(booking.car_id).photo.key %>" alt="Image booking" style="height:100%;width:100%"/> </a>
	        	</a>
          <div class="postcard__text">
              <h1 class="postcard__title blue">
                <p>Booking #<%= booking.id %></p>
              </h1>
              <ul class="postcard__tagbox">
                <li class="tag__item"><i class="far fa-calendar-alt mr-2"></i><%=booking.start_date%></li>
                <li class="tag__item"><i class="fas fa-flag-checkered mr-2"></i><%=booking.end_date%></li>
                  <a href="https://www.google.com/maps/search/?api=1&<%=booking.pickup_location%>" target="_blank"><li class="tag__item"><i class="fas fa-map-marker-alt mr-2"></i><%=booking.pickup_location%></li></a>
                <li class="tag__item"><i class="fas fa-car-crash mr-2"></i><%= booking.insurance%></li>
              </ul>
          </div>
         </div>
    </div>
    <% end %>
  </div>
</div>
     

app/views/bookings/new.html.erb
<div class="container-fluid ">

<div class="row p-3 m-5 w-50 mx-auto postcard blue">

<div class="col-12">
<h1><%= @car.brand %> <%= @car.model %> <%= @car.year %></h1>
<%= simple_form_for([@car, @booking]) do |f| %>
  <p>Start date</p>
  <%= f.datetime_field :start_date, class: "form-control form-btn border-light rounded-pill m-1" %><br>
  <p>End date</p>
  <%= f.datetime_field :end_date, class: "form-control form-btn border-light rounded-pill m-1" %><br>
  <%= f.input :pickup_location, placeholder: "Pick up location", class: "form-control form-btn" %><br>
  <span>Do you want insurance?</span>
  <%= f.check_box :insurance%><br>
  <%= f.button :submit, class: "btn btn-dark mx-3" %>
<% end %>

<%=%>


</div>
</div>
</div>

app/views/bookings/show.html.erb
<%=@booking %>

app/views/cars/index.html.erb
<div class="container-fluid">

<div class="row">
		<div class="col px-0">
			<h1 class="ml-0 title-showpage px-0" style="background-color: white">&nbsp;OUR CARS</h1>
			</div></div>
<div class="row mt-3">
<div class="col-7">
	<% @cars.each do |car| %>
	<div class="postcard blue">
		<a class="postcard__img_link" href="#">
		<a href="<%=car_path(car.id)%>">	<img class="postcard__img" src="<%= cl_image_path car.photo.key%>" alt="car photo" style="height:100%;width:100%" /> </a>
		</a>
		<div class="postcard__text">
			<h1 class="postcard__title blue">
				<a href="<%=car_path(car.id)%>"><%=car.brand%>&nbsp;<%=car.model%>&nbsp;<%=car.year%></a>
			</h1>
			<div class="postcard__subtitle small">
			</div>
			<div class="postcard__bar"></div>
			<div class="postcard__preview-txt text-left"> <%=car.description%></div>
			<ul class="postcard__tagbox">
		    <% if car.status == "busy" %>
						<li class="tag__item "></i>Car is not available!</li>
					<% else %>
						<li class="tag__item "><a href="<%= new_car_booking_path(car) %>"><i class="fas fa-car mr-2"></i>Rent me</a></li>
						<li class="tag__item"><i class="fas fa-map-marker-alt mr-2"></i><%=car.location%></li>
				<% end %>
			</ul>
    </div>
		</div>
	<% end %>

</div>
<div class="col-5">
	<div class="mapcard" id="map" style="width: 100%; height: 600px;  position: sticky; top: 10px;" data-markers="<%= @markers.to_json %>"
		data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
	</div>
</div>

</div></div></div>

app/views/cars/new.html.erb
<div class="container justify-content-center">

<div class="row p-3 m-5 w-75 mx-auto postcard blue">
<div class="col-12">
<h1>Add your car</h1>
<%= simple_form_for([@car]) do |f| %>
  <%= f.input :title, placeholder: "Model, brand, year" %><br>
  <%= f.input :model, placeholder: "Model" %><br>
  <%= f.input :brand, placeholder: "Describe your car" %><br>
  <%= f.input :year, placeholder: "Describe your car" %><br>
  <%= f.input :location, placeholder: "Describe your car" %><br>
  <%= f.input :price, placeholder: "Describe your car" %><br>
  <%= f.input :description, placeholder: "Describe your car" %><br>
  <%= f.input :photo, as: :file %><br>
  <%= f.submit %>
<% end %>
</div>
</div>
</div>

app/views/cars/show.html.erb
<style>
	.show {
		background-image: url("<%= cl_image_path @car.photo.key %>");
		height: 100%;
		background-position: center;
		background-repeat: no-repeat;
		background-size: cover;
	}
</style>


<div class="container-fluid mb-5 pb-5 show">
	<br>
	<div class="row">
		<div class="col px-0">
			<h1 class="ml-0 title-showpage px-0" style="background-color: white">&nbsp;<%= @car.title %></h1>
			<div>
				<div class="row mx-0">
					<div class="col-2 mx-0"></div>
					<div class="col-8">

						<article class="postcard blue mt-4">

							<img class="postcard__img" src="<%= cl_image_path @car.photo.key %>" alt="car photo" />

							<div class="postcard__text">
								<h1 class="postcard__title blue"><%= @car.brand %>&nbsp;<%= @car.model %>: <%= @car.year %></h1>
								<div class="postcard__subtitle small">

									<i class="fas fa-dollar-sign mr-1"></i><%= @car.price %>

								</div>
								<div class="postcard__bar"></div>
								<div class="postcard__preview-txt"><%= @car.description %></div>
								<ul class="postcard__tagbox">
									<a href="<%= new_car_booking_path(@car) %>">
										<li class="tag__item"><i class="fas fa-car mr-2"></i>Rent this car</li>
									</a>
									<li class="tag__item"><i class="fas fa-map-marker-alt mr-2"></i><%= @car.location %></li>
									<!--	<li class="tag__item"><i class="fas fa-clock mr-2"></i>55 mins.</li>
				<li class="tag__item play blue">
					<a href="#"><i class="fas fa-play mr-2"></i>Play Episode</a> -->
									</li>
								</ul>
							</div>
						</article>
						<div class="mapcard mt-4 mb-5">

						<div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @marker.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
	</div>
						</div><br><br><br>
					</div>

				</div>
			</div>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>HotWheels</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  <%= stylesheet_pack_tag 'application' %>
  <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@600&display=swap" rel="stylesheet">
</head>

<body>

  <nav class="navbar navbar-expand-sm navbar-light bg-light px-0 d-flex">
    <a class="navbar-brand"
      href="<%= root_path %>"><%=image_tag("hot-wheel-logo.png", alt: "hot wheel logo", style: 'height: 70px;')%></a>
    <button class="navbar-toggler text-right" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">
      <div class="w-25">
        <%= form_tag cars_path, method: :get do %>
          <%= text_field_tag :query, '', class: "form-control border-dark rounded-pill",
          placeholder: "...Search by Brand or Model"
          %>
        </div>
        <div class="rounded">
          <%= submit_tag "Search", class: "btn btn btn-dark mx-3" %>
        <% end %>
      </div>
      <div class="nav-item text-right mr-sm-2 d-flex justify-content-end">
        <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false" src="https://bit.ly/3fOsxWn" />
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="<%= cars_path %>">All cars</a>

                <a class="dropdown-item" href="<%= bookings_path(@user) %>">All Bookings</a>
                <a class="dropdown-item" href="<%= new_car_path(@user) %>">Rent Your Car</a>

                <a class="dropdown-item" <%= link_to "Log out", destroy_user_session_path, :method => :delete %> </a>
              </div>
            </li>
          </ul>
        </div>
        <% else %>
        <a href="#" data-toggle="modal" data-target="#modal">
          <button type="add-btn" class="btn btn-dark mx-3">Log in</button> </a>
        <a href="#" data-toggle="modal" data-target="#modalUp"> <button type="sign-btn" class="btn btn-dark">Sign
            Up</button></a>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <%= render "devise/login"%>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="modalUp" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <%= render "devise/signUp"%>
        </div>
      </div>
    </div>
  </div>

  <%= yield %>

  <br><br>
  <div class="container-fluid">
    <div class="row navbar" style="background-color: #F4F4F4">
      <div class="col-4">
        <p class="copy" id="left-copy">&copy; HotWheels 2021</p>
      </div>
      <div class="col-4">
      </div>
      <div class="col-4 text-right">
        <p><a href="<%= root_path %>">
            <button type="button" class="btn btn-secondary btn-sm btn-footer" id="home-btn">Home Page
            </button>
          </a>
          <a href="mailto:email@email.com">
            <button type="button" class="btn btn-secondary btn-sm btn-footer" id="contact-btn">Contact Us
            </button>
          </a>
        </p>
      </div>
    </div>
  </div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</body>

</html>

app/views/pages/home.html.erb
<div class="container-fluid mb-0 pb-0 ">
  <div class="row">
    <div class="col">
      <p class="ml-4 mt-3 main-title-css"> <b>Hot Wheels</b></p>
      <p class="ml-4 main-title-css"><span style="font-size:80%">Rent the car of your dreams!</p>
    </div>
  </div>
</div>
<br>


<div id="carouselExampleIndicators" class="carousel slide autoplay " data-interval="2000" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>

  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="<%= cl_image_path @car.photo.key%>" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="<%= cl_image_path @car2.photo.key%>" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="<%= cl_image_path @car3.photo.key%>" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="review-containter d-flex justify-content-center mt-5">
  <div class="row">
    <div class="col-sm-6">
      <blockquote class="blockquote blockquote-custom bg-white p-5 shadow rounded">
        <div class="blockquote-custom-icon bg-info shadow-sm"><i class="fa fa-quote-left text-white"></i></div>
        <p class="mb-0 mt-2 font-italic">"When my Tesla breaks down Hot Wheels is always there for me. I absolutely
          recommend this service <a href="#" class="text-info">@HotWheels</a>."</p>
        <footer class="blockquote-footer pt-4 mt-4 border-top">Elon Musk
        </footer>
        <img src="https://wallpapercave.com/wp/wp2048439.jpg" class="card-trip-user avatar-bordered" />
      </blockquote>
    </div>
    <div class="col-sm-6">
      <blockquote class="blockquote blockquote-custom bg-white p-5 shadow rounded">
        <div class="blockquote-custom-icon bg-info shadow-sm"><i class="fa fa-quote-left text-white"></i></div>
        <p class="mb-0 mt-2 font-italic">"Hot Wheels have made my trip vacations easier when I need to rent a car<a
            href="#" class="text-info">@HotWheels</a>."</p>
        <footer class="blockquote-footer pt-4 mt-4 border-top">Ace Ventura
        </footer>
        <img src="https://bit.ly/3fuAH7p" class="card-trip-user avatar-bordered" />
      </blockquote>
    </div>
    <div class="col-sm-6 mt-3">
      <blockquote class="blockquote blockquote-custom bg-white p-5 shadow rounded">
        <div class="blockquote-custom-icon bg-info shadow-sm"><i class="fa fa-quote-left text-white"></i></div>
        <p class="mb-0 mt-2 font-italic">"Renting out my car to people has never been easier. The experience is
          amazing<a href="#" class="text-info">@HotWheels</a>."</p>
        <footer class="blockquote-footer pt-4 mt-4 border-top">Joe "DMT" Rogan
        </footer>
        <img src="https://bit.ly/2R6IcIg" class="card-trip-user avatar-bordered" />
      </blockquote>
    </div>
    <div class="col-sm-6 mt-3">
      <blockquote class="blockquote blockquote-custom bg-white p-5 shadow rounded">
        <div class="blockquote-custom-icon bg-info shadow-sm"><i class="fa fa-quote-left text-white"></i></div>
        <p class="mb-0 mt-2 font-italic">"As a car owner I have never been so satified with a service like Hot Wheels
          everything is easy and fast<a href="#" class="text-info">@HotWheels</a>."</p>
        <footer class="blockquote-footer pt-4 mt-4 border-top">Big Ed
        </footer>
        <img src="https://i.redd.it/fj1yfji0dpo61.jpg" class="card-trip-user avatar-bordered" />
      </blockquote>
    </div>
  </div>
</div>